workflows:
  repvx_app_preview:
    name: RepVX Dual Platform Preview
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      vars:
        BUILD_DIR: build
    scripts:
      - name: Flutter ortamını hazırla
        script: |
          flutter clean
          flutter pub get
      - name: Android .apk oluştur (debug)
        script: flutter build apk --debug
      - name: iOS .app oluştur (simülatör için)
        script: flutter build ios --debug --simulator
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
      - build/ios/iphonesimulator/Runner.app

  repvx_play_release:
    name: RepVX Play Store Release
    max_build_duration: 60
    environment:
      flutter: stable
      groups:
        - google_credentials
    scripts:
      - name: Bağımlılıkları yükle
        script: flutter pub get
      - name: Release .aab oluştur
        script: flutter build appbundle --release
    artifacts:
      - build/app/outputs/bundle/release/app-release.aab
    publishing:
      google_play:
        credentials: $GOOGLE_PLAY_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: true

  repvx_ios_release:
    name: RepVX iOS Release
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - appstore_credentials
      vars:
        TEAM_ID: XHWQQ94L6F  # Sizin Team ID'niz
        
    scripts:
      - name: Flutter deps
        script: flutter pub get

      # TEK SATIR KOMUT: Tüm imzalama parametrelerini shell hatası olmadan iletiyoruz
      - name: Build iOS for archive (Final Solution)
        script: flutter build ipa --release -t lib/main.dart DEVELOPMENT_TEAM="$TEAM_ID" OTHER_CODE_SIGN_FLAGS="--keychain /Library/Keychains/CM.keychain"

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        submit_to_app_store: false